language: rust
rust:
  - nightly
cache: cargo
before_install: 
  - rustup target add wasm32-unknown-unknown --toolchain nightly
script:
  - cargo +nightly build --verbose --release --target wasm32-unknown-unknown